### ISSUE TITLE
Add autoupdater for core & plugins

### ISSUE THREAD

**Issue by beaver-dev** [featherbb/featherbb#101]
- Use script to delete featherbb folder and replace it with new one, downloaded from github in tmp dir
- Same for plugins, with a bool param to indicate if the plugin needs to be uninstalled then reinstalled or just update its files

**Comment by adaur** [comment]
https://github.com/VisualAppeal/PHP-Auto-Update

TODO: handle DB upgrades

**Comment by beaver-dev** [comment]
Add translations

**Comment by beaver-dev** [comment]
Minor improvements can be made in the future (especially in views), but it is functionnal.
