### ISSUE TITLE
Handle .htaccess absence

### ISSUE THREAD

**Issue by beaver-dev** [featherbb/featherbb#105]
http://forums.featherbb.org/topic/79/fatal-error-upon-installation-of-the-beta4-version
- Take a closer look at Slim built-in functions to add /index.php before each urls
- Or add a check in Core middleware if .htaccess is present and function_exists('apache_get_modules') (maybe too mutch payload ?)

**Comment by adaur** [comment]
That's what we did before you introduced the nice urlFor then pathFor function:

https://github.com/featherbb/featherbb/blob/1.0.0-beta.2/include/functions.php#L1795

**Comment by beaver-dev** [comment]
To confirm what was said in Gitter : it will be re-introduced in the Router interface with a ForumSettings() key to add or not the /index.php in urls.

**Comment by beaver-dev** [comment]
After benchmarking the two codes, it turns off that directly checking Apache mod_rewrite function is faster than getting a ForumSettings key.
