### ISSUE TITLE
Improve SEO URLs in topic views

### ISSUE THREAD

**Issue by beaver-dev** [featherbb/featherbb#111]
When viewing a topic, all posts on a same page should have the same URL except for their hash.

For example instead of 
- _http://localhost/post/1#p1_
- _http://localhost/post/2#p2_
- _http://localhost/post/3#p3_
- ...

we could have 
- _http://localhost/topic/[1|topic-title][/page-1]#p1_
- _http://localhost/topic/[1|topic-title][/page-1]#p2_
- _http://localhost/topic/[1|topic-title][/page-1]#p3_  

This would avoid making a new request each time we click on a post href inside a topic page, since in the end we stay on the same page with the same data (and make things simpler in the to-come PJAX loader ;) )

**Comment by adaur** [comment]
Agree

**Comment by franzliedke** [comment]
There's a good reason that's how it's done in FluxBB, if you're interested. ;)

The way you ~~suppose~~ suggest, permalinks will not be true permalinks, as different users can have different settings of how many posts they want to see per page...

**Comment by beaver-dev** [comment]
Indeed, it makes more sense! I'll try to find another way to do what I want in the "fluid-nav" plugin, and maybe add a bit of JS in the core to avoid making new requests when clicking on anchors inside a page.
Still, we could include the topic title in posts URLs.
Thanks for your answer :)

**Comment by adaur** [comment]
Thanks Franz. However, I don't see how a topic-x-subject#p1 would be different depending on the user?

**Comment by beaver-dev** [comment]
Let's say user A wants to display 30 messages per page in topic views, and user B 75 messages. If the permalink is like _http://localhost/topic/topic-title/page-1#p70_, user B will correctly see the 70th message since it is in page 1, but for user A it will be in page 3.

**Comment by adaur** [comment]
Then maybe we should rename the actual post to topic/id/subject/post/id#id if you want a url more explicit. The choice is up to you on this one :)

**Comment by beaver-dev** [comment]
Done with 280f14b95b105041e51df340c4c0159fdcdc8cd8 and previous commits !
