### ISSUE TITLE
Strange behaviour when topics are merged

### ISSUE THREAD

**Issue by Poffen** [featherbb/featherbb#127]
When I tested the moderator functions on a fresh install of the current development branch I came across a strange behaviour when topics are merged. If 2 topics are merged and the "Leave redirect topic(s)" option is ticked, two identical copies of the parent forum are displayed. This seems to occur only if the "redirect" option is chosen. If I delete the redirect (Moved topic), then the copy of the forum disappear.

Putte

**Comment by adaur** [comment]
I'll look into it, thanks.

**Comment by adaur** [comment]
I cannot reproduce the issue you describe. Could you please provide screenshots? Thanks.

**Comment by Poffen** [comment]
Hi,
I did a fresh install of the development version (as of now) and created a couple of topics, while keeping the default category and forum created during installation. 

I than navigated to the moderator view, ticked the topics to merge (first image), ticked the option to leave a redirect and than hit the Index Tab at the top. This resulted in duplicate versions of the only forum that exists (second image). As I said, this seems to occur only when I tick the "redirect option".

![merging-topics](https://cloud.githubusercontent.com/assets/3382610/15905372/f32f8c22-2db4-11e6-8e98-cad0ddf888a3.png)

![duplicate_forums](https://cloud.githubusercontent.com/assets/3382610/15905389/fd59caa0-2db4-11e6-8f77-760b155ff0a5.png)

**Comment by adaur** [comment]
Ok, I can reproduce it now. I will let you know when it is fixed. Thanks for your participation :)
