### ISSUE TITLE
The option to render custom template files in a new style doesn't work properly

### ISSUE THREAD

**Issue by Poffen** [featherbb/featherbb#129]
Hi again,

I tested the option to use custom template files in a new (custom) style on the latest development version of FeatherBB. I did this by copying and renaming the default FeatherBB style folder (to MyStyle) and then I added a copy of the default View folder to the 'MyStyle' folder and renamed it to 'view'. 

I was able to display the header.php and the footer.php files of the 'view' folder in MyStyle, but none of the other template files.

Putte

**Comment by Poffen** [comment]
I did some testing (var_dump) and it seems that the command to set the user style `$this->setStyle(User::getPref('style'));` under the display method `public function display($nested = true)` in featherbb/Core/View.php (lines 160-162) does not take effect, thus failing to add the view files (of the new style) to the stack. If I move the entire if-clause to the top of the `public function getTemplatesDirectory()` method (lines 122-), everything seems to work as intended.

**Comment by adaur** [comment]
You are definitely right. I came to the same conclusion while moving the block in the __construct function, but your solution is much better.

Many thanks!
