### ISSUE TITLE
Move the moderator controls to the forum and topic view files

### ISSUE THREAD

**Issue by Poffen** [featherbb/featherbb#131]
Hi adaur,

I think it's better to display the navigation links of the moderator controls on the forum and topic view templates (see images below), instead of in the footer template file as it is now.

Also, I think all mod controls should be included in the forum mod controls, including the "Stick" and "Unstick" functions (see below).

What do you think? If you like the idea of moving/extending the mod controls, then I can submit a commit.

Poffen

![mod controls-forum](https://cloud.githubusercontent.com/assets/3382610/15985335/17ac61d8-2fea-11e6-9855-f3c1ea17395d.png)

![mod controls-topic](https://cloud.githubusercontent.com/assets/3382610/15985338/2144b646-2fea-11e6-8ced-53d8fbfaa7b5.png)

![additional mod controls-forum](https://cloud.githubusercontent.com/assets/3382610/15985343/3a3070f0-2fea-11e6-886c-1d7ed9f777cf.png)

**Comment by adaur** [comment]
If you have the code ready, I'll merge it quickly :)

**Comment by Poffen** [comment]
Hi again,

I've just submitted a pull request.

Poffen
