### ISSUE TITLE
Topic subscription doesn't work

### ISSUE THREAD

**Issue by Poffen** [featherbb/featherbb#134]
The option to subscribe to a topic doesn't seem to work.

Poffen

**Comment by adaur** [comment]
Kudos!

**Comment by adaur** [comment]
Woops, wrong issue ticket :)

**Comment by adaur** [comment]
What do you mean by not working? The emails are not sent?

**Comment by adaur** [comment]
Actually, the modification I've done to fix the permissions might have solved this. I'm waiting for your return :)

**Comment by Poffen** [comment]
Yes, the issue was that no email is sent when another user submit a reply to a subscribed topic. And the recent changes of the code hasn't fixed this.

**Comment by adaur** [comment]
OK, thank you. I'll investigate.

**Comment by adaur** [comment]
We're good now :-)
