### ISSUE TITLE
The option in the user profile to show subscriptions is broken

### ISSUE THREAD

**Issue by Poffen** [featherbb/featherbb#137]
Hi,

The option in a user's profile to show subscriptions (Profile > Essentials > Show all subscriptions) doesn't work and returns a fatal error (Call to a member function find_one_col() on a non-object in /var/www/html/featherbb/Model/Search.php on line 655). This seems to be due to a typo of the variable passed to the hook on line 654 in the model, which I presume should read: `$subscriber_name = Container::get('hooks')->fireDB('model.search.get_search_results_subscriber_name', $subscriber_name);` and not: `$subscriber_name = Container::get('hooks')->fireDB('model.search.get_search_results_subscriber_name', $result);`.

However, if I correct this, the number of subscribed topics returned does not correspond with the user pref (disp.topics), as I would expect, but varies from page to page (in my case 1-3 topics per page, regardless of what page I'm on).

Poffen

**Comment by adaur** [comment]
The pagination issue should be gone by now, however are you able to reproduce this issue with other searches?

**Comment by Poffen** [comment]
I did check other search types and the subscription link was apparently the only one that returned an error. However, the changes you've just made to the code returns a new error: `SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'featherbb.t.last_post' which is not in SELECT list; this is incompatible with DISTINCT`

**Comment by adaur** [comment]
Strange, it worked fine for me. Are you using mysql? Which version?

**Comment by Poffen** [comment]
Yes, I'm using MySQL on a local setup. Version: 5.7.12-0ubuntu1.1 - (Ubuntu)

**Comment by adaur** [comment]
I found that this option displayed all the topics, not just the subscribed ones.

Hopefully, ca9ab7221f3ef91368b7db96f8c7f86ca5d2405d fixes it.

Are you still having the error? I'm unable to reproduce it with MySQL 5.6.17. I'd be interested to get your database if this is still relevant.

**Comment by Poffen** [comment]
Hi again,

I'll test this later, when I have some spare time. 

I fixed the MySql error I had by [this fix](https://github.com/Piwigo/Piwigo/issues/376). Unfortunately, I don't have access at the moment to the laptop where I have the 5.7.12 version of MySQL (and hence the database), but I'll send it to you when I can. What do you need? A zip of the database, or more than that?

Poffen

**Comment by adaur** [comment]
Hm this seems to be DB-related. Yes, sure I can see if I can reproduce it with your DB. You can send it at admin at featherbb dot org :)
