### ISSUE TITLE
Splitting posts returns a sql error

### ISSUE THREAD

**Issue by Poffen** [featherbb/featherbb#139]
An error is returned when I split posts: `SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'num_replies' at row 1`

It seems that this is due to a typo on line 799 in the Topic.php model: `->set_expr('num_replies', 'num_replies-'.$num_posts_splitted-1);`

Changing this line to: `->set_expr('num_replies', 'num_replies+'.($num_posts_splitted - 1));` seems to fix the issue.

Poffen

**Comment by adaur** [comment]
Hi,

Thanks for the catch. Looking at FluxBB makes me think this line should be num_replies=(num posts-1)

https://github.com/fluxbb/fluxbb/blob/master/moderate.php#L210

Can you see if this fixes it?

**Comment by Poffen** [comment]
Yes, the patch works.
