### ISSUE TITLE
Auth[Login] Page Issue

### ISSUE THREAD

**Issue by in1side** [featherbb/featherbb#141]
Greetings.I saw that if you enter incorrect password/username you will get a blank page, instead of message.

**Comment by adaur** [comment]
Hello!

Which branch did you use? I think this has been fixed in the dev branch: https://github.com/featherbb/featherbb/commit/8b1db50ae5faac25567663d4c25fb867b647e0b8

**Comment by in1side** [comment]
I am using the official one.

**Comment by adaur** [comment]
Can you try with the development branch please?

**Comment by in1side** [comment]
Of course I will.
PS:
Working like a charm.
