### ISSUE TITLE
Add a notification system

### ISSUE THREAD

**Issue by adaur** [featherbb/featherbb#24]
We should use Slim's flash messages after redirect

**Comment by adaur** [comment]
https://github.com/featherbb/featherbb/commit/3b6fa55034c5c30757be023ad0221d6ee7abf873

It needs a redesign :)

**Comment by adaur** [comment]
We could use simple JS to do a fancy fade out effect, what do you think? @beaver-dev

**Comment by beaver-dev** [comment]
Sure, I'll take a look at your work tomorrow but JS notifications is a great idea ! However this must be in addition of a static HTML notification, for example in a `<noscript>` tag for users who can't/don't want to enable JS of course :)
Plus, I frequently use a great JS notifications library : [toastr](https://github.com/CodeSeven/toastr) which we could take some ideas if needed.

**Comment by beaver-dev** [comment]
Pull request sent on new-db-layer branch :)
Fade in/out features, and top-right sticky alert box.

**Comment by adaur** [comment]
Thanks! I'll review it asap :)
