### ISSUE TITLE
Mettre à jour Slim en 2.6.2

### ISSUE THREAD

**Issue by Machou** [featherbb/featherbb#51]
Bonjour

Pense à mettre a jour en 2.6.2 ton Slim Framework :D

**Comment by adaur** [comment]
Salut, 

N'est-ce pas déjà le cas ? Si tu vas sur leur github et que tu sélectionnes la dernière release en 2.x, Slim.php indique 2.6.1 au lieu de 2.6.2

**Comment by al3xLvs** [comment]
Utilises composer pour dev, plus simple pour mettre à jour.

**Comment by adaur** [comment]
J'avais prévu de le faire oui. Le problème étant que j'aimerais conserver une version prête à marcher sur le repo (donc commit le vendor ?)

**Comment by al3xLvs** [comment]
Mouais, le repo pour moi c'est plus pour les dev.
Ce que je ferais c'est, à chaque pre-release, un zip avec toutes les dépenses d'installé via composer.

Vérifies mais je crois que sur github tu peux ajouter des zip avec les releases note.
D'ailleurs c'est comme ça pour les programmes que l'on compile. Y a pas de binaire dans le repo.

L'avantage de composer c'est qu'il a un autoloader ^^

note : d'autant plus que la version de slim 3 aura plus de dépendance donc pour mettre à jour ça sera surement plus compliqué (mais pas insurmontable non plus je le concède)

**Comment by adaur** [comment]
Je sais que c'est très mal vu, mais on s'adresse à une population d'admins lambda, pas de développeurs confirmés.

J'aime beaucoup la possibilité de faire une release en quelques clics sans me préoccuper du reste, et commit le vendor permettrait cela, sans compter qu'il n'y aura pas énormément de dépendances, donc pas des centaines de fichiers non plus.

La vraie question, c'est: est-ce qu'il serait toujours possible de référencer le paquet sur packagist.org et de l'installer via un composer install, le vendor étant dans le repo, et est-ce qu'il pourra mettre à jour les dépendances si elles sont dépassées?

**Comment by al3xLvs** [comment]
Pour mettre à jour il faudra gérer ça avec ton fichier composer.json en fonction des règles que tu auras indiqué.

Après si tu commit le dossier vendor là je sais pas trop. composer télécharge via git je crois.
Mais peut-être que ça risque de faire des conflits, le mieux serait de faire un test.
