### ISSUE TITLE
Manage plugins from admin panel

### ISSUE THREAD

**Issue by beaver-dev** [featherbb/featherbb#66]
Display a list of available plugins (read folder content), with a button to install/disable/uninstall them if needed.
More ideas & screenshots on this later :)

**Comment by beaver-dev** [comment]
I am working on a new branch using Composer to manage plugins, as we already mentioned it to autoload some core elements.
Plugins will use Composer too, with a custom "featherbb-plugin" type.
They might use [Composer custom installers](https://github.com/composer/installers) as a pull request will be sent to their repo soon.

**Comment by adaur** [comment]
We should do a vendor directory where we will store all the classes (DB layer, cache, etc). Each of them should be a separate repo and be made available via Packagist don't you think?

The remaining question is: do we still publish them in the "official" repo?

**Comment by beaver-dev** [comment]
Yes, that's how I see it too in the future. But we can let the repo as-is for now, as composer allow to load classes from custom locations even if they are not composer-compatible.

**Comment by beaver-dev** [comment]
Note for later : use a [Factory pattern](https://openclassrooms.com/courses/programmez-en-oriente-objet-en-php/les-design-patterns) to load activated plugins
