### ISSUE TITLE
New BBcode parser

### ISSUE THREAD

**Issue by beaver-dev** [featherbb/featherbb#78]
The BBcode is not anymore parsed on development branch, and it surely will be a pain to find where and when it occurred...
So instead of trying to restore the old FluxBB system we could use a more OO approach, e.g. forking and extending [this](https://github.com/golonka/BBCodeParser) library, or [this one](http://jbbcode.com/).
What do you think ?

**Comment by franzliedke** [comment]
@adaur You used Jeff's parser, right? If so, I'd advise you guys to try to make it work, he did a great job and I'm fairly certain this is high quality code. :)

**Comment by beaver-dev** [comment]
Hi Franz,
We wanted to in the first place, as this code is really well integrated into FluxBB we wouldn't have had to rewrite a lot of code. When looking more in details into it I saw that eventually it was really not object oriented, and didn't feel like rewriting all of it :P
But [this file](https://github.com/fluxbb/fluxbb/blob/master/include/parser.php) is different from the one we have on the current repo, and seems easier to integrate into our "OO" vision of FeatherBB ! Do you know which one is the most recent ? I was just trying to make **golonka** library work as you wrote your message, and it obviously needs a loooot of work to be as complete and well integrated as Jeff's code... If @adaur agrees, I'll be glad to use it instead. Thank you for your comment, I wouldn't have noticed that otherwise.
And good luck for Flarum, it seems a great project ;)

**Comment by adaur** [comment]
@beaver-dev the file you're referring to is the current FluxBB parser. I integrated Jeff's one because of its cool features.

Maybe we could use some work done for FluxBB 2.0 before the decision to use Laravel? 
https://github.com/fluxbb/parser/

**Comment by adaur** [comment]
And it's done!

https://github.com/featherbb/featherbb/commit/fc4cbf43613888462dd1cbe6a30c6296e1d774d5

There is still a sprintf bug.
