### ISSUE TITLE
Create a Marketplace for plugins, themes, and languages

### ISSUE THREAD

**Issue by beaver-dev** [featherbb/featherbb#94]
In the first place we wanted to list content of featherbb/plugins repo, and propose download via cURL/git/composer.
The problem is that github doesn't allow to download a single folder from a repo, we have to find another way.
- First lead : use SVN instead of Github, as it seems to be easier to get a particular directory from the trunk. That's how Wordpress manages plugins.
- Second lead : use the github repo only to display available plugins and some infos about them : author, name, download url (basically, the feather.json file content), letting the original code into the author github repo. Maybe we could add a backup archive in the featherbb/plugins repo, in case the author deletes his code.
- Third lead : create a **_plugins.featherbb.org**_ subdomain, using Slim (v3 when ready ?) for a more complete solution : user ratings, categories... The plugins would be hosted on the main site server, taking the risk to lose everything if it is down, or moved.

But maybe I've missed something about downloading only part of a repo, so if you have other ideas... ;-)

**Comment by adaur** [comment]
What if we cloned the repo on our server and we make the users download from it?

**Comment by beaver-dev** [comment]
You mean clone each plugin separately ? Yes why not ! So to install plugins, the forum admins could use two different ways :
- Use the future built-in marketplace in admin panel, which would search for available plugins (hosted on featherbb.org server), then download them via cURL.
- Locally download plugin from author's github account, and upload it manually to their forum plugins directory

In both cases, a **_plugins.featherbb.org**_ subdomain should be created to simplify the marketplace searches : use an API to sort by rating, number of downloads, category, or display more informations about using the plugin for example.
We're not in a hurry though, I suggest we wait for Slim v3 to be stable enough to code the Marketplace subdomain since we won't be using github after all.

**Comment by adaur** [comment]
@beaver-dev @capkokoon hi folks! I hope you're doing well.

I plan to work on FeatherBB during my holidays, feel free to join me in order to (finally) release the first stable version :)

**Comment by beaver-dev** [comment]
Hi!
I'll have some time to code on FeatherBB soon, here is another idea for the marketplace :
- To propose a new plugin or theme, the developpers create a repo on their github account, and then submit it on **market.featherbb.org** subdomain with the repo URL, plus other optionnal infos (screenshots, instructions...). If this repo is valid and secure, we clone it into the FeatherBB github account and publish it to Packagist, so that it can be easilly installed and updated via composer.
- To update their plugins, the devs make a pull request to the repo on our account. Here again, if it is valid we accept the pull request : thanks to github hooks, the packagist repo will also be updated, so we won't have too mutch work to do.
- For a plugin to be valid, it has to be a valid Composer package with tags and/or zip releases, and of course don't represent security issues on FeatherBB. It should also be into a "featherbb-plugin" vendor name, e.g.: _featherbb-plugin/private-messages_, so that we can search for all folders in /vendor/featherbb-plugin to get available plugins from admin panel.
- The market.featherbb.org subdomain could grab main infos of plugins from packagist (name, description, authors, number of downloads...) completed with other metadata. The admin panel would request this URL to browse plugins and themes, then run "composer install featherbb-plugins/plugin-name".

I played a bit with Slim v3 (stable version 3.1 has been released), it seems perfect to build the marketplace site and could be a base for a future FeatherBB upgrade!

How about that ?

**Comment by adaur** [comment]
Have you seen what I've done so far? It's functional with a repo per plug-in and it's very easy to manage. 

Glad to hear from you :)

**Comment by beaver-dev** [comment]
I came back recently from a month without internet so I didn't see, but yes what you've done is pretty mutch what I thought about :) The two repos now just need to be published to packagist.org, then we can start coding the Marketplace with Slim v3 if you agree with the idea! 
Of course we could download zip balls directly from Github and decompress them in the plugins or themes directory, but as we wanted to use Composer (is it still the case ?) we'd better start working towards this IMO.

**Comment by adaur** [comment]
Of course! I'm not familiar with Composer, so I'll need your help about this. I tried Slim 3 a bit, but the 'no getInstance' thing is troubling me.

**Comment by beaver-dev** [comment]
Don't worry about that, I've found a small library to access all the Slim and FeatherBB features statically from anywhere as we talked earlier ;) => https://github.com/johnstevenson/slim-static
It only needed a few adjustments to get working with v3, but now we can do Request::getHeaders(), Router::get('url')->setName('foo'), User::register(), Post::addReply() or whatever we want else! It is already working in my Marketplace draft, I'll publish it to Github very soon.
In the meantime could you create an account on https://packagist.org/register/ ?

**Comment by adaur** [comment]
It's done. Give me your email so I can send you the details :)

I've done more work on your PM plugin, I'll push it asap.

**Comment by beaver-dev** [comment]
stutz.valentin@gmail.com

**Comment by beaver-dev** [comment]
See https://github.com/featherbb/marketplace.
