### ISSUE TITLE
Can't register on forums.featherbb.org

### ISSUE THREAD

**Issue by bohwaz** [featherbb/featherbb#95]
Hey, I encountered two bugs while trying to register for an account on http://forums.featherbb.org/register/

My login was bohwaz and my email featherbb.bohwaz@miam.kd2.org

First time I got a message saying that the SMTP server said that my email address is invalid. Well, no it's not.

Then I tried again, and I got "A new user was registered with the same IP address as you within the last hour". Well no I didn't register since my email address was deemed invalid.

So I see there is a problem here as the subscription should not be inserted in database if it fails, as you are then blocked from trying again. And my email address is not invalid by the way :)

**Comment by beaver-dev** [comment]
Hi,

Problem should be fixed with the latest updates. If you can't login, ask for your account deletion to the support, create a new account or request this issue to be re-opened if you wish ;)

beaver

**Comment by bohwaz** [comment]
OK so I requested a new password, got it by email:

```
Hello bohwaz,

You have requested to have a new password assigned to your account in the discussion forum at
http://forums.featherbb.org/. If you didn't request this or if you don't want to change your password you
should just ignore this message. Only if you visit the activation page below will your password be changed.

Your new password is: ZInFiv13Subz

To change your password, please visit the following page:
http://forums.featherbb.org/user/424/action/change_pass?key=uFSvJFq4
```

So I clicked the link, which directed me to the login form, weird OK, then I tried the supplied password, not good either.

So I probably struck on two other bugs :)

**Comment by beaver-dev** [comment]
They should be fixed in the development branch since a few weeks, but I can't remember when exactly. If you've got a development environment on your local machine (Apache & co installed, or WAMP/MAMP/LAMP...), please install the dev branch, test again and tell me if it works. Make sure your email settings are correctly set in the admin panel.
Else, wait for the official forum to switch to the latest release when next Beta version is ready :)
