### ISSUE TITLE
IRC channel?

### ISSUE THREAD

**Issue by bohwaz** [featherbb/featherbb#96]
Is there an IRC channel where people can discuss the project?

I tried the web chat but it asks for my private Github email address and other authorizations that I don't want to give, so I can't connect.

If there is no IRC channel I'm willing to register one on Freenode or Geeknode or whatever is that's OK.

**Comment by adaur** [comment]
Hi,

There is no IRC at the moment because we use Gitter. It's free, convenient and it works just fine with GitHub. Many projects use it :)

**Comment by bohwaz** [comment]
Unfortunately it requires giving it access to my GitHub account.

**Comment by adaur** [comment]
This is needed to register to their system, and you can revoke the authorization at any moment. 

You can create a fake account if you don't feel comfortable, but an IRC server would require personal information (email address) as well. 

https://github.com/gitterHQ/gitter/issues/27
