### ISSUE TITLE
Fatal error: Can't use method return value in write context in featherbb/Controller/Install.php on line 42

### ISSUE THREAD

**Issue by bohwaz** [featherbb/featherbb#97]
Yup that's the error I get when I try featherBB beta 3 or git repository. Using PHP 5.4.45.

**Comment by adaur** [comment]
I can't reproduce it on the dev branch, sorry.

However, I fixed a bug with DB prefixes: https://github.com/featherbb/featherbb/commit/6e414d5ec8a026e0293bd89bf482d18c119e56b0

**Comment by franzliedke** [comment]
@adaur Try with an older PHP version ;)

**Comment by adaur** [comment]
I'm using PHP 5.5.12 at the moment. Does this happen with PHP 5.3 and PHP 5.4 ?

**Comment by adaur** [comment]
OK, can you try changing

if (!empty($this->feather->request->post('choose_lang'))) {

to

if ($this->feather->request->post('choose_lang')) {

and see if that fixes it?
