### ISSUE TITLE
Error on your forums ;)

### ISSUE THREAD

**Issue by scriptzteam** [featherbb/featherbb#98]
Notice: Trying to get property of non-object in /var/www/featherbb/extern.php on line 242

Notice: Trying to get property of non-object in /var/www/featherbb/extern.php on line 246

Fatal error: Uncaught PDOException: could not find driver in /var/www/featherbb/featherbb/Core/Database.php:263 Stack trace: #0 /var/www/featherbb/featherbb/Core/Database.php(263): PDO->__construct('sqlite::memory:', NULL, NULL, NULL) #1 /var/www/featherbb/featherbb/Core/Database.php(245): DB::_setup_db('default') #2 /var/www/featherbb/extern.php(545): DB::for_table('topics') #3 {main} thrown in /var/www/featherbb/featherbb/Core/Database.php on line 263

**Comment by adaur** [comment]
Thanks for the report. Extern.php will be rewritten from scratch, in order to have a cleaner API :)
